spring:
  datasource:
    book:
      url: jdbc:mysql://localhost:3306/j2
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
